@startuml

node "Navigateur web" {
	frame clientCode {
		[index.js]
	}
}

node "Serveur (linux)" {
	component frontend
	interface http
	frontend - http
	database "Kafka" {
		interface "chatt-input"
		interface "chatt-output"
	}
	component zookeper
	component stream


	frontend -down-> [chatt-input]
	frontend <-up- [chatt-output]

	[chatt-input] -down-> stream
	stream -up-> [chatt-output]

	Kafka->zookeper
}

[http] .up.> clientCode
[index.js] --> [http] : Post
[http] --> [index.js] : EventSource

@enduml
